name: aphero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  uses-material-design: true
  fonts:
    - family: chau philomene
      fonts:
        - asset: assets/fonts/chauphilomene.ttf
        - asset: assets/fonts/chauphilomeneitalic.ttf
          style: italic
